services:
  web:
    image: nginx
    ports:
      - 82:80
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

  php-fpm:
    container_name: php-fpm
    build: ./Docker/php
    volumes:
      - ./:/var/www/html
      - .//Docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini

  postgres:
    image: postgres:13.1
    container_name: postgres_db
    volumes:
      - ./Docker/postgres/data_new:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5437:5432


